/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server_Interface.View;

import Server_Interface.Controller.InterfaceController;

/**
 *
 * @author PersonalCastro
 */
public class VistaServidor extends javax.swing.JFrame {


    InterfaceController controladorDeInterfaz;
    
    public VistaServidor() {
        initComponents();
        controladorDeInterfaz = new InterfaceController();
        this.jTextField_IPBD.setText("clasedam2.ddns.net"); //clasedam2.ddns.net (carlos)
        this.jTextField_Puerto.setText("39999");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Bienvenido = new javax.swing.JLabel();
        jTextField_Puerto = new javax.swing.JTextField();
        jLabel_Puerto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_debug = new javax.swing.JTextArea();
        jLabel_debug = new javax.swing.JLabel();
        jButton_Play = new javax.swing.JButton();
        jButton_Stop = new javax.swing.JButton();
        jLabel_runningServers = new javax.swing.JLabel();
        jComboBoxPorts = new javax.swing.JComboBox<>();
        jLabel_Puerto1 = new javax.swing.JLabel();
        jTextField_IPBD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel_Bienvenido.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel_Bienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Bienvenido.setText("Bienvenido al Servidor de CristoMessenger");

        jLabel_Puerto.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel_Puerto.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Puerto.setText("Puerto del Servidor : ");

        jTextArea_debug.setEditable(false);
        jTextArea_debug.setColumns(20);
        jTextArea_debug.setRows(5);
        jScrollPane1.setViewportView(jTextArea_debug);

        jLabel_debug.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel_debug.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_debug.setText("Server Debug");

        jButton_Play.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jButton_Play.setText("Play");
        jButton_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayActionPerformed(evt);
            }
        });

        jButton_Stop.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jButton_Stop.setText("Stop");
        jButton_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StopActionPerformed(evt);
            }
        });

        jLabel_runningServers.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel_runningServers.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_runningServers.setText("Running Servers");

        jLabel_Puerto1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel_Puerto1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Puerto1.setText("Ip de la Base de Datos : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_debug)
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Puerto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Puerto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_IPBD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128)
                        .addComponent(jButton_Play, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_runningServers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPorts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel_Bienvenido)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel_Bienvenido)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Play)
                            .addComponent(jButton_Stop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_debug)
                            .addComponent(jLabel_runningServers))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Puerto)
                            .addComponent(jTextField_Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Puerto1)
                            .addComponent(jTextField_IPBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StopActionPerformed
        
        String port = this.jTextField_Puerto.getText();
        
        if(!controladorDeInterfaz.tryStopServer_controller(port)){
            this.jTextArea_debug.append("Something wrong has just happened when you were trying to stop the server\n");
        }else{
            this.jTextArea_debug.append("Server has successfully stopped\n");
            
            
            if(controladorDeInterfaz.portSearch_Controller(port) != -1){
                this.jComboBoxPorts.remove(controladorDeInterfaz.portSearch_Controller(port));
                this.controladorDeInterfaz.eliminatePort_Controller(port);
            }
            

        }
        
        //System.out.println("\n\n");
    }//GEN-LAST:event_jButton_StopActionPerformed

    private void jButton_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayActionPerformed

        tryPlayServer_view();
        
    }//GEN-LAST:event_jButton_PlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Play;
    private javax.swing.JButton jButton_Stop;
    private javax.swing.JComboBox<String> jComboBoxPorts;
    private javax.swing.JLabel jLabel_Bienvenido;
    private javax.swing.JLabel jLabel_Puerto;
    private javax.swing.JLabel jLabel_Puerto1;
    private javax.swing.JLabel jLabel_debug;
    private javax.swing.JLabel jLabel_runningServers;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea_debug;
    private javax.swing.JTextField jTextField_IPBD;
    private javax.swing.JTextField jTextField_Puerto;
    // End of variables declaration//GEN-END:variables

    private void tryPlayServer_view() {
        
        String port = this.jTextField_Puerto.getText();
        String ip_bd = this.jTextField_IPBD.getText();
        
        if(!controladorDeInterfaz.notEmptyPort(port)){
            this.jTextArea_debug.append("You might have not been inicialized Port Param\n");
        }else if (!controladorDeInterfaz.lessThan6NumbersPort(port)){
            this.jTextArea_debug.append("It's Imposible to use this Port. Size shoud be under 6 digits\n");
        }else if(!controladorDeInterfaz.portOppen(port)){
            this.jTextArea_debug.append("This port has already been openned\n");
        }else if(!controladorDeInterfaz.tryPlayServer_controller(port, ip_bd)){
            this.jTextArea_debug.append("Something wrong has just happened with this Port. Try other Port\n");
        }else{
            
            this.jTextArea_debug.append("Server is Running right now\n");
            this.jComboBoxPorts.addItem(port);

        }
                
    }
}
