package Hibernate;
// Generated 05-mar-2020 13:53:03 by Hibernate Tools 4.3.1



/**
 * FriendId generated by hbm2java
 */
public class FriendId  implements java.io.Serializable {


     private String idUserOrig;
     private String idUserDest;

    public FriendId() {
    }

    public FriendId(String idUserOrig, String idUserDest) {
       this.idUserOrig = idUserOrig;
       this.idUserDest = idUserDest;
    }
   
    public String getIdUserOrig() {
        return this.idUserOrig;
    }
    
    public void setIdUserOrig(String idUserOrig) {
        this.idUserOrig = idUserOrig;
    }
    public String getIdUserDest() {
        return this.idUserDest;
    }
    
    public void setIdUserDest(String idUserDest) {
        this.idUserDest = idUserDest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendId) ) return false;
		 FriendId castOther = ( FriendId ) other; 
         
		 return ( (this.getIdUserOrig()==castOther.getIdUserOrig()) || ( this.getIdUserOrig()!=null && castOther.getIdUserOrig()!=null && this.getIdUserOrig().equals(castOther.getIdUserOrig()) ) )
 && ( (this.getIdUserDest()==castOther.getIdUserDest()) || ( this.getIdUserDest()!=null && castOther.getIdUserDest()!=null && this.getIdUserDest().equals(castOther.getIdUserDest()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdUserOrig() == null ? 0 : this.getIdUserOrig().hashCode() );
         result = 37 * result + ( getIdUserDest() == null ? 0 : this.getIdUserDest().hashCode() );
         return result;
   }   


}


