package Hibernate;
// Generated 05-mar-2020 13:53:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MessageId generated by hbm2java
 */
public class MessageId  implements java.io.Serializable {


     private String idUserOrig;
     private String idUserDest;
     private Date datetime;

    public MessageId() {
    }

    public MessageId(String idUserOrig, String idUserDest, Date datetime) {
       this.idUserOrig = idUserOrig;
       this.idUserDest = idUserDest;
       this.datetime = datetime;
    }
   
    public String getIdUserOrig() {
        return this.idUserOrig;
    }
    
    public void setIdUserOrig(String idUserOrig) {
        this.idUserOrig = idUserOrig;
    }
    public String getIdUserDest() {
        return this.idUserDest;
    }
    
    public void setIdUserDest(String idUserDest) {
        this.idUserDest = idUserDest;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MessageId) ) return false;
		 MessageId castOther = ( MessageId ) other; 
         
		 return ( (this.getIdUserOrig()==castOther.getIdUserOrig()) || ( this.getIdUserOrig()!=null && castOther.getIdUserOrig()!=null && this.getIdUserOrig().equals(castOther.getIdUserOrig()) ) )
 && ( (this.getIdUserDest()==castOther.getIdUserDest()) || ( this.getIdUserDest()!=null && castOther.getIdUserDest()!=null && this.getIdUserDest().equals(castOther.getIdUserDest()) ) )
 && ( (this.getDatetime()==castOther.getDatetime()) || ( this.getDatetime()!=null && castOther.getDatetime()!=null && this.getDatetime().equals(castOther.getDatetime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdUserOrig() == null ? 0 : this.getIdUserOrig().hashCode() );
         result = 37 * result + ( getIdUserDest() == null ? 0 : this.getIdUserDest().hashCode() );
         result = 37 * result + ( getDatetime() == null ? 0 : this.getDatetime().hashCode() );
         return result;
   }   


}


