package Hibernate;
// Generated 05-mar-2020 13:53:03 by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private MessageId id;
     private User userByIdUserOrig;
     private User userByIdUserDest;
     private Integer readMsg;
     private Integer sent;
     private String text;

    public Message() {
    }

	
    public Message(MessageId id, User userByIdUserOrig, User userByIdUserDest) {
        this.id = id;
        this.userByIdUserOrig = userByIdUserOrig;
        this.userByIdUserDest = userByIdUserDest;
    }
    public Message(MessageId id, User userByIdUserOrig, User userByIdUserDest, Integer readMsg, Integer sent, String text) {
       this.id = id;
       this.userByIdUserOrig = userByIdUserOrig;
       this.userByIdUserDest = userByIdUserDest;
       this.readMsg = readMsg;
       this.sent = sent;
       this.text = text;
    }
   
    public MessageId getId() {
        return this.id;
    }
    
    public void setId(MessageId id) {
        this.id = id;
    }
    public User getUserByIdUserOrig() {
        return this.userByIdUserOrig;
    }
    
    public void setUserByIdUserOrig(User userByIdUserOrig) {
        this.userByIdUserOrig = userByIdUserOrig;
    }
    public User getUserByIdUserDest() {
        return this.userByIdUserDest;
    }
    
    public void setUserByIdUserDest(User userByIdUserDest) {
        this.userByIdUserDest = userByIdUserDest;
    }
    public Integer getReadMsg() {
        return this.readMsg;
    }
    
    public void setReadMsg(Integer readMsg) {
        this.readMsg = readMsg;
    }
    public Integer getSent() {
        return this.sent;
    }
    
    public void setSent(Integer sent) {
        this.sent = sent;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


